using System.Buffers.Binary;
using System.Text.Json;
using Launcher.Core.Tests.Theming;
using Launcher.Core.Theming;

namespace Launcher.Core.Tests.Models;

/// <summary>
/// The committed built-in models (generated by the Godot project's box template tool, into the built-in theme and the
/// test theme) follow the model spec (A7): one scene, named slot materials, the origin at the bottom centre, the
/// largest side 1 m, slot UVs within 0..1, and the template budgets. Reads only the GLB JSON chunk, as ModelInspector
/// will.
/// </summary>
public sealed class BuiltInModelTests
{
    private static readonly string[] Slots = [.. MediaSlots.Names];

    /// <summary>
    /// Every game template's model in the built-in theme and the test theme, as (theme folder, model path), once each
    /// (two templates can share a model).
    /// </summary>
    public static TheoryData<string, string> Templates()
    {
        var data = new TheoryData<string, string>();
        foreach (var folder in (string[])[ThemeFixtures.BuiltInFolder, ThemeFixtures.SlotShowcaseFolder])
        {
            var theme = ThemeFixtures.Load(folder);
            foreach (var model in theme.Templates.Values.Select(t => t.Model).Distinct(StringComparer.Ordinal))
            {
                data.Add(folder, model);
            }
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(Templates))]
    public void Every_box_template_follows_the_model_spec(string folder, string modelPath)
    {
        var id = Path.GetFileNameWithoutExtension(modelPath);
        var model = Load(folder, modelPath);

        Assert.Contains("cover", model.Materials);
        Assert.True(model.Materials.Count <= 4, $"{id} has {model.Materials.Count} materials; the budget is 4.");
        Assert.True(model.Triangles <= 2000, $"{id} has {model.Triangles} triangles; the budget is 2,000.");
        AssertShape(id, model);
    }

    [Fact]
    public void Every_model_in_the_Godot_project_is_exported_as_the_file_itself()
    {
        // The app reads a built-in theme's .glb from the PCK as a file (A6 Locations). Godot's default import for a new
        // .glb is a scene, which the export packs instead of the file, so the theme can't find it and drops the
        // template: DOS fell back to the DVD case in the export, though the editor (reading the folder) was right.
        var project = Path.Combine(ThemeFixtures.RepoRoot, "godot");
        var models = Directory.GetFiles(project, "*.glb", SearchOption.AllDirectories)
            .Where(path => !path.Contains($"{Path.DirectorySeparatorChar}.godot{Path.DirectorySeparatorChar}", StringComparison.Ordinal))
            .ToList();

        Assert.NotEmpty(models);
        Assert.All(models, path =>
        {
            var import = path + ".import";
            Assert.True(File.Exists(import), $"{import} is missing.");
            Assert.True(
                File.ReadAllText(import).Contains("importer=\"keep\"", StringComparison.Ordinal),
                $"{import} must say importer=\"keep\" (Import dock: Keep File), or the export leaves the .glb out.");
        });
    }

    [Fact]
    public void The_generic_system_model_follows_the_model_spec()
    {
        var model = Load(ThemeFixtures.BuiltInFolder, ThemeFixtures.Load(ThemeFixtures.BuiltInFolder).Defaults.SystemModel!);

        Assert.Contains("label", model.Materials);
        Assert.True(model.Triangles <= 30_000);
        AssertShape("generic", model);
    }

    private static void AssertShape(string id, Model model)
    {
        const float Tolerance = 0.001f;
        Assert.Equal(1, model.Scenes);
        Assert.InRange(model.Min[1], -Tolerance, Tolerance);
        Assert.InRange(model.Min[0] + model.Max[0], -Tolerance, Tolerance);
        Assert.InRange(model.Min[2] + model.Max[2], -Tolerance, Tolerance);
        var largest = Math.Max(model.Max[0] - model.Min[0], Math.Max(model.Max[1] - model.Min[1], model.Max[2] - model.Min[2]));
        Assert.InRange(largest, 1 - Tolerance, 1 + Tolerance);
        Assert.All(model.Materials, name => Assert.True(Slots.Contains(name) || name == "case", $"{id}: unexpected material '{name}'"));
        foreach (var slot in model.SlotUvRanges)
        {
            Assert.True(slot.Value.Min >= 0 && slot.Value.Max <= 1, $"{id}: {slot.Key}'s UVs leave 0..1.");
        }

        foreach (var (name, aspect) in model.Aspects)
        {
            Assert.True(aspect > 0, $"{id}: {name} has no extras.aspect.");
        }
    }

    private sealed record Model(
        List<string> Materials,
        int Triangles,
        int Scenes,
        float[] Min,
        float[] Max,
        Dictionary<string, (float Min, float Max)> SlotUvRanges,
        Dictionary<string, float> Aspects);

    private static Model Load(string folder, string relative)
    {
        var path = Path.Combine(folder, relative.Replace('/', Path.DirectorySeparatorChar));
        var bytes = File.ReadAllBytes(path);
        Assert.True(bytes.AsSpan(0, 4).SequenceEqual("glTF"u8), $"{path} isn't a GLB.");
        Assert.Equal(2u, BinaryPrimitives.ReadUInt32LittleEndian(bytes.AsSpan(4)));
        var jsonLength = BinaryPrimitives.ReadInt32LittleEndian(bytes.AsSpan(12));
        Assert.True(bytes.AsSpan(16, 4).SequenceEqual("JSON"u8));
        using var json = JsonDocument.Parse(bytes.AsMemory(20, jsonLength));
        var root = json.RootElement;

        var materials = new List<string>();
        var aspects = new Dictionary<string, float>(StringComparer.Ordinal);
        foreach (var material in root.GetProperty("materials").EnumerateArray())
        {
            var name = material.GetProperty("name").GetString()!;
            materials.Add(name);
            if (Slots.Contains(name))
            {
                aspects[name] = material.TryGetProperty("extras", out var extras) && extras.TryGetProperty("aspect", out var aspect)
                    ? aspect.GetSingle()
                    : 0;
                var factor = material.GetProperty("pbrMetallicRoughness").GetProperty("baseColorFactor");
                Assert.All(factor.EnumerateArray(), c => Assert.Equal(1.0, c.GetDouble(), 3));
            }
        }

        var accessors = root.GetProperty("accessors");
        var min = new[] { float.MaxValue, float.MaxValue, float.MaxValue };
        var max = new[] { float.MinValue, float.MinValue, float.MinValue };
        var uvs = new Dictionary<string, (float Min, float Max)>(StringComparer.Ordinal);
        var triangles = 0;
        foreach (var mesh in root.GetProperty("meshes").EnumerateArray())
        {
            foreach (var primitive in mesh.GetProperty("primitives").EnumerateArray())
            {
                var attributes = primitive.GetProperty("attributes");
                var position = accessors[attributes.GetProperty("POSITION").GetInt32()];
                for (var axis = 0; axis < 3; axis++)
                {
                    min[axis] = Math.Min(min[axis], position.GetProperty("min")[axis].GetSingle());
                    max[axis] = Math.Max(max[axis], position.GetProperty("max")[axis].GetSingle());
                }

                triangles += accessors[primitive.GetProperty("indices").GetInt32()].GetProperty("count").GetInt32() / 3;
                var name = materials[primitive.GetProperty("material").GetInt32()];
                if (Slots.Contains(name))
                {
                    var uv = accessors[attributes.GetProperty("TEXCOORD_0").GetInt32()];
                    var low = Math.Min(uv.GetProperty("min")[0].GetSingle(), uv.GetProperty("min")[1].GetSingle());
                    var high = Math.Max(uv.GetProperty("max")[0].GetSingle(), uv.GetProperty("max")[1].GetSingle());
                    uvs[name] = (low, high);
                }
            }
        }

        return new Model(materials, triangles, root.GetProperty("scenes").GetArrayLength(), min, max, uvs, aspects);
    }
}
