# Writes src/Launcher.Core/Scraping/BuiltInAccounts.Release.g.cs: ScreenScraper's developer credentials, built into
# a release (docs/ARCHITECTURE.md A5, "Secrets"). The release workflow runs it before it builds, with the values from
# the repository's secrets in SCREENSCRAPER_DEV_ID and SCREENSCRAPER_DEV_PASSWORD. The file is gitignored: never
# commit it. Each value is XORed with a random key made for this build, so it isn't plain text in the DLL.
#
#   -Required   fail if the variables aren't set (a tagged release); otherwise the build has no built-in credentials
#   -Remove     delete the file, so a local build has none again
#
# It never prints a value.
param(
    [switch] $Required,
    [switch] $Remove
)

$ErrorActionPreference = 'Stop'
$path = Join-Path $PSScriptRoot '..\src\Launcher.Core\Scraping\BuiltInAccounts.Release.g.cs'
$path = [IO.Path]::GetFullPath($path)

if ($Remove) {
    if (Test-Path $path) { Remove-Item $path }
    Write-Host "Removed $path, if it was there: builds have no built-in credentials."
    exit 0
}

$devId = $env:SCREENSCRAPER_DEV_ID
$devPassword = $env:SCREENSCRAPER_DEV_PASSWORD
$hasId = -not [string]::IsNullOrWhiteSpace($devId)
$hasPassword = -not [string]::IsNullOrWhiteSpace($devPassword)

if ($hasId -ne $hasPassword) {
    throw 'Only one of SCREENSCRAPER_DEV_ID and SCREENSCRAPER_DEV_PASSWORD is set: set both, or neither.'
}

if (-not $hasId) {
    if ($Required) {
        throw 'SCREENSCRAPER_DEV_ID and SCREENSCRAPER_DEV_PASSWORD aren''t set (the repository secrets of the same names), and a release needs them.'
    }

    if (Test-Path $path) { Remove-Item $path }
    Write-Warning 'SCREENSCRAPER_DEV_ID and SCREENSCRAPER_DEV_PASSWORD aren''t set: this build has no built-in ScreenScraper developer credentials.'
    exit 0
}

$random = [Security.Cryptography.RandomNumberGenerator]::Create()

# The C# arguments for one value: its UTF-8 bytes XORed with a key as long, then the key.
function Scrambled([string] $value) {
    $bytes = [Text.Encoding]::UTF8.GetBytes($value.Trim())
    $key = New-Object byte[] $bytes.Length
    $random.GetBytes($key)
    $data = New-Object byte[] $bytes.Length
    for ($i = 0; $i -lt $bytes.Length; $i++) { $data[$i] = $bytes[$i] -bxor $key[$i] }
    $hex = { param($b) ($b | ForEach-Object { '0x{0:X2}' -f $_ }) -join ', ' }
    "[$(& $hex $data)], [$(& $hex $key)]"
}

$text = @"
// <auto-generated/>
// Written by tools/write-built-in-accounts.ps1 for a release build. Gitignored: never commit it.
#nullable enable

namespace Launcher.Core.Scraping;

internal static partial class BuiltInAccounts
{
    static partial void ScreenScraper(ref string? devId, ref string? devPassword)
    {
        devId = Decode($(Scrambled $devId));
        devPassword = Decode($(Scrambled $devPassword));
    }
}

"@ -replace "`r`n", "`n"

$random.Dispose()
[IO.File]::WriteAllText($path, $text, (New-Object Text.UTF8Encoding $false))
Write-Host "Wrote $path (ScreenScraper's developer credentials, scrambled)."
